name: constructor-env

channels:
  - conda-forge

dependencies:
  - mamba
# - constructor
# https://github.com/conda/constructor/pull/477
# - pip
# - pip:
#   - https://github.com/conda/constructor/archive/refs/heads/fix-env-mode.zip
